version: 2

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - run:
          name: Test
          command: |
            echo "Hi CircleCi"
